image: gitpod/workspace-full

tasks:
  - before: sudo apt-get update && sudo apt-get install nim && nimble install docopt
    command: nim c main

vscode:
  extensions:
    - nimsaem.nimvscode
    - chouzz.vscode-innosetup