image: gitpod/workspace-full

tasks:
  - name: Startup
    init: |
      sudo apt-get update
      sudo apt-get install nim
      nimble install docopt
      
    command: nim c main

vscode:
  extensions:
    - nimsaem.nimvscod
    - chouzz.vscode-innosetup
    - yzhang.markdown-all-in-one
    - DavidAnson.vscode-markdownlint
