image: gitpod/workspace-full

tasks:
  - name: Startup
    init: |
      curl https://nim-lang.org/choosenim/init.sh -o choosenim
      chmod +x choosenim
      ./choosenim
      export PATH=/home/$USER/.nimble/bin:$PATH
      nimble install docopt -y
      nimble install yaml -y
      cd src
      
    command: nim c main

vscode:
  extensions:
    - nimsaem.nimvscode
    - chouzz.vscode-innosetup
    - yzhang.markdown-all-in-one
    - DavidAnson.vscode-markdownlint
    - ecmel.vscode-html-css
