image: gitpod/workspace-full

tasks:
  - name: Startup
    init: |
      sudo apt update
      sudo apt install nim
      nimble install docopt -y
      nimble install yaml -y
      cd src
      
    command: nim c main

vscode:
  extensions:
    - nimsaem.nimvscode
    - chouzz.vscode-innosetup
    - yzhang.markdown-all-in-one
    - DavidAnson.vscode-markdownlint
