image: gitpod/workspace-full

tasks:
  - name: Startup
    init: |
      sudo apt update
      sudo apt install nim
      sudo apt install rename
      nimble install docopt -y
      cd src
      rename -v 's/main/grid9/' *.nim
      
    command: nim c grid9

vscode:
  extensions:
    - nimsaem.nimvscode
    - chouzz.vscode-innosetup
    - yzhang.markdown-all-in-one
    - DavidAnson.vscode-markdownlint
