[metadata]
author = "MrEnder"
description = "Prints out the character for the glyth that you give it."
version = "1.0.2"
showmetadata = true

[config]
advancedParse = true
dontCache = false
echoGridMod = true
noLog = false
verbosity = 1