[metadata]
author = "MrEnder"
description = "Shows how to use a xor effect on grids."
version = "1.0.0"
showmetadata = true

[config]
advancedParse = true
dontCache = false
echoGridMod = true
noLog = false
verbosity = 1