[metadata]
author = "MrEnder"
description = "Showcases the use of the delay command in Grid9."
version = "1.0.2"
showmetadata = true
minGrid9Ver = "2023.003"

[config]
advancedParse = true
dontCache = false
echoGridMod = false
noLog = false
verbosity = 1