[metadata]
author = "MrEnder"
description = "Prints A and B"
version = "1.0.0"
showmetadata = true
minGrid9Ver = "2022.023"

[config]
advancedParse = true
dontCache = false
echoGridMod = false
noLog = false
verbosity = 1