[metadata]
author = "MrEnder"
description = "Prints out the character for the GLYPH that you give it."
version = "1.0.2"
showmetadata = true
minGrid9Ver = "2022.023"

[config]
advancedParse = true
dontCache = false
echoGridMod = true
noLog = false
verbosity = 1