[metadata]
author = "MrEnder"
description = "Uses a if ladder to print out diffrent characters"
version = "1.0.5"
showmetadata = true
minGrid9Ver = "2022.023"

[config]
advancedParse = true
dontCache = false
echoGridMod = true
noLog = false
verbosity = 1