[metadata]
author = "MrEnder"
description = "Prints out a random character"
version = "1.0.1"
showmetadata = true
minGrid9Ver = "2022.023"

[config]
advancedParse = true
dontCache = false
echoGridMod = true
noLog = false
verbosity = 1