name: Nightly Release
on:
  schedule:
  - cron: '59 4 * * *'

jobs:
  NightlyReleaseLinux:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: '1.6.x'

    - name: Install Dependencies
      run: |
        nimble install docopt -Y
        nimble install parsetoml -Y

    - name: Build
      run: |
        cd ${{ github.workspace }}
        git clone https://github.com/MrEnder0/Grid9.git
        cd Grid9/src
        nim c -d:release main

    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: Grid9_Nightly_Linux
        path: Grid9/src/main

  NightlyReleaseWindows:
    runs-on: windows-latest
    steps:
    - name: Install Nim
      run: |
        $url = "https://github.com/dom96/choosenim/releases/download/v0.8.4/choosenim-0.8.4_windows_amd64.exe"
        Invoke-WebRequest -Uri $url -OutFile "choosenim.exe"
        ./choosenim stable --firstInstall -y

    - name: Build
      run: |
        cd C:\Users\runneradmin\.nimble\bin
        ./nimble install docopt -y
        ./nimble install parsetoml -y
        git clone https://github.com/MrEnder0/Grid9.git
        ./nim c -d:release Grid9/src/main

    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: Grid9_Nightly_Windows
        path: C:/Users/runneradmin/.nimble/bin/Grid9/src/main.exe